# Generated by Django 5.0.3 on 2024-03-28 20:32

import Xray.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="uploads/",
                        validators=[Xray.models.validate_content_file],
                    ),
                ),
                (
                    "fracture",
                    models.CharField(
                        blank=True,
                        choices=[("fractured", "Fractured"), ("normal", "Normal")],
                        max_length=20,
                    ),
                ),
                ("bone_type", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
