# Generated by Django 5.0.3 on 2024-03-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Xray", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
            ],
        ),
        migrations.DeleteModel(
            name="ImageAnalysis",
        ),
    ]
